name = "LegendrePolynomials"
uuid = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
version = "0.4.1"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Aqua = "0.5"
HyperDualNumbers = "4"
OffsetArrays = "1"
PerformanceTestTools = "0.1"
QuadGK = "2"
SpecialFunctions = "1, 2"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
HyperDualNumbers = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"
PerformanceTestTools = "dc46b164-d16f-48ec-a853-60448fc869fe"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "HyperDualNumbers", "PerformanceTestTools", "Test", "QuadGK"]
